/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scan;
        System.out.println("Вы любите собак?");
        
        String a=scan.nextLine();
        System.out.println(a);
    }
}
